# Generated by Django 2.1 on 2018-08-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='home_web',
            table='auth_user',
        ),
    ]
